### ISSUE TITLE
Для Душанбе: несколько одинаковых пар на неделе

### ISSUE THREAD

**Issue by IgneusCougar** [devind-team/eleden#13]
Необходимо сделать функционал, который позволит выбирать, сколько одинаковых пар стоит на неделе, например, лекция по высшей математике в понедельник и среду. Возможно, сделать галочку на этапе создания расписания "Несколько пар на неделе" или что-то подобное. Но это как один из вариантов отображения функционал

**Comment by Luferov** [comment]
Не целесообразно.
