### ISSUE TITLE
Написать джанго команду для фикстур

### ISSUE THREAD

**Issue by MiloslavskiySergey** [devind-team/eleden#334]
Необходимо написать джанго команду для применения всех фикстур в проекте

**Comment by Luferov** [comment]
Такой команды нет?

**Comment by MiloslavskiySergey** [comment]
нету, когда переходили на фикстуры были переписаны только файлы

**Comment by Luferov** [comment]
а на dcis это есть?

**Comment by Luferov** [comment]
у вас есть понимание как это сделать правильно?

**Comment by MiloslavskiySergey** [comment]
на dcis этого тоже нету
примерное понимание есть
