### ISSUE TITLE
Баг с удалением образовательной программы и дисциплины

### ISSUE THREAD

**Issue by demenkovakate** [devind-team/eleden#40]
При удалении образовательной программы или дисциплины в настройках происходит переход на страницу с их списком, где присутствует удаленная образовательная программа или дисциплина

**Comment by Luferov** [comment]
Запись там присутствует, так как не удаляется из кеша.
Я эту проблему решил следующим образом. Там, где Вы удаляете запишем вот такой запрос:
https://github.com/devind-team/dcis/blob/768c9223578e635e383c326f55325762edd9ba25/client/pages/dcis/periods/_periodId/settings.vue#L172-L182

Обратите внимание, там передается `query` в запросе.
На самой странице:
https://github.com/devind-team/dcis/blob/768c9223578e635e383c326f55325762edd9ba25/client/pages/dcis/projects/_projectId/periods.vue#L66-L78
