### ISSUE TITLE
Изменение папки client/.nuxt -> client/nuxt-dist

### ISSUE THREAD

**Issue by demenkovakate** [devind-team/eleden#41]
Для поддержки автоимпорта и статических подсказок стандартная папка сборки проекта переименовывается из .nuxt в nuxt-dist.

**Comment by Luferov** [comment]
Подождите чуть-чуть, я хочу кое что проверить

**Comment by Luferov** [comment]
Удалите `.nuxt` из файла `client/.eslintignore` и этого будет достаточно.

**Comment by Luferov** [comment]
Выполняйте переименование `.nuxt` -> `nuxt-dist`:

- `tscofig.json` 
- `nuxt.config.ts` -> `buildDir: 'nuxt-dist'`
