### ISSUE TITLE
Переписать components/eleden/ac на composition api 

### ISSUE THREAD

**Issue by demenkovakate** [devind-team/eleden#75]
teams:
- [x] AddJob.vue
- [x] AddJobPost.vue
- [x] AddStatusHistory.vue
- [x] AddTeams.vue
- [x] AddUsers.vue
- [x] ChangeTeam.vue
- [x] ChangeTeamEduProgram.vue
- [x] ChangeTeamResponsibleUsers.vue
- [x] DeleteTeam.vue
- [x] GenerateNewPasswords.vue
- [x] StatusHistory.vue
- [x] TeamActions.vue
- [x] UnloadTeams.vue
- [x] UploadJobs.vue
- [x] UploadJobsUser.vue

user:
- [x] ChangeAvatar.vue
- [x] ConfirmedByUser.vue
- [x] Jobs.vue
- [x] Personalities.vue
- [x] PortfolioFiles.vue
- [x] Responsible.vue

**Comment by Luferov** [comment]
А где PR?
