### ISSUE TITLE
Изменить структуру сайта и дизайн главной страницы

### ISSUE THREAD

**Issue by Luferov** [devind-team/eleden#87]
- [x] На главной странице разделить новости и новости, связанные с конференциями, мероприятиями, предложениями о публикации.

- Новости – сбор новостей, материалов, посвященных разделам науки, сбор научно-популярных публикации, касающихся новостей ИИ.
- Мероприятия – информация о мероприятиях, съездах, юбилеях, награждениях.
  - Конференции/Воркшопы – актуальные конференции, а также информация о прошедших.
  - Семинары
- Библиотека (все, что не подпадает в разделы ниже).
  - Статьи авторов, не имеющие конкретной привязки к конференциям и семинарам.
  - Материалы, связанные с историей РАИИ.
  - Публикации членов РАИИ (По основным направления ИИ, которые должен определить научный совет и/или руководство).
  - Учебные материалы.
  - Старые журналы, в том числе «Новости ИИ».
  - Возможно, другие архивные материалы (какие?)
- Ведущие ученые РАИИ информация о знаковых представителях РАИИ.
- РАИИ об искусственном интеллекте
  - Интервью – с членами РАИИ.
  - Публикации в сторонних источниках о членах РАИИ.
  - Участие членов РАИИ в публичных мероприятиях, выступления в медиа.
- О РАИИ/О нас
  - Устав и основополагающие документы (как стать членом ассоциации).
  - Информация об актуальном списке членов (ссылка на каждого члена РАИИ).
  - Информация о списке региональных отделений РАИИ.
  - Информация о РАИИ в социальных сетях.
  - Связи с другими ассоциациями, например, Европейской.
  - Реквизиты для оплаты членских взносов/пожертвований.

 - [x] Перенести контент в соответствии с новой структурой

**Comment by Luferov** [comment]
Как движение за 27 дней?

**Comment by IgneusCougar** [comment]
У меня не получается сделать так, чтобы меню динамически перемещалось наверх, оно остается на одном и том же расстоянии, а еще у меня все сломалось, потому что для сборов нужен был питон 10, а у меня все было на 9

**Comment by IgneusCougar** [comment]
Борисов сказал оставить меню как есть, ему так нравится
