### ISSUE TITLE
Не обновляется кэш при удалении записи

### ISSUE THREAD

**Issue by surguh** [devind-team/eleden#9]
https://github.com/devind-team/eleden/blob/634a494ab8ba88c5e48a218fe19bd99b7f9fab49/client/pages/eleden/edu_programs/_edu_program_id/settings.vue#L15-L22
https://github.com/devind-team/eleden/blob/634a494ab8ba88c5e48a218fe19bd99b7f9fab49/client/pages/eleden/edu_programs/_edu_program_id/settings.vue#L134-L141

**Comment by Luferov** [comment]
По хорошему, это еще нужно сразу на composition api переписать.

**Comment by Luferov** [comment]
И вообще, Вы достали какой-то код, который честно говоря сомнительно выглядит.
